# Generated by Django 3.2.7 on 2021-09-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signuppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=100)),
                ('Business_Type', models.CharField(max_length=100)),
                ('Nature_of_Business', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('UserType', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('C_password', models.CharField(max_length=100)),
            ],
        ),
    ]
