# Generated by Django 3.2.7 on 2021-10-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0004_alter_signuppage_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuppage',
            name='Email_id',
        ),
    ]
